### PR TITLE
Make accept-invite viewname configurable in django settings

### PR DESCRIPTION
**Pull request by BartoszCki**
https://github.com/jazzband/django-invitations/pull/108

### CODE REVIEW

**Comment by valberg** [comment]
pre-commit.ci autofix

**Comment by valberg** [comment]
Great @BartoszCki! I just remembered that we should put it in the README as well (soon to be converted to docs). Can you add that to the PR? https://github.com/jazzband/django-invitations#additional-configuration

**Comment by BartoszCki** [comment]
> Great @BartoszCki! I just remembered that we should put it in the README as well (soon to be converted to docs). Can you add that to the PR? https://github.com/jazzband/django-invitations#additional-configuration

Done. Sorry I pushed with force by mistake and overwritten changes made by pre-commit.ci :/

**Comment by valberg** [comment]
pre-commit.ci autofix

**Comment by valberg** [comment]
No worries @BartoszCki 

Thanks for the PR! I'll merge when everything is green :)

**Pull request merged**
