### PR TITLE
Update import for django 4.0

### PR DESCRIPTION
**Pull request by saschahofmann**
`force_text` has finally been removed making the library incompatible with django 4

### CODE REVIEW

**Comment by ntoll** [comment]
I'm using @saschahofmann's branch and can confirm the changes work with Django 4.0. Would be wonderful to get this merged and have a new release to PyPI. :rocket:

**Comment by valberg** [comment]
This is blocking our upgrade to Django 4.0. I would love to help in any way I can to get a new version of django-invitations out the door! :)

**Comment by saschahofmann** [comment]
I am afraid there is nothing to be done here until maintainers take a look. I would recommend using this branch for now.

**Comment by valberg** [comment]
It looks like the project is in the process of joining Jazzband, so hopefully that means that we can do a release soon.

**Comment by valberg** [comment]
For reference: https://github.com/jazzband/help/issues/237

**Pull request merged**
